// state_info.js

// Microservice: (Get natural highest point) data

// JSON format: {state: state, highest_natural_point: highest_natural_point, elevation: elevation, prominence: prominence, location: location, rank: rank}

export const state_info = {
  AL: {
    state: "Alabama",
    highest_natural_point: "Cheaha Mountain",
    elevation: ": 2,413 ft (735 m)",
    prominence: "1,445 ft (440 m)",
    rank: 35,
    location: "the town Delta",
  },
  AK: {
    state: "Alaska",
    highest_natural_point: "Denali (formerly Mount McKinley)",
    elevation: ": 20,310 ft (6,190 m) top of snow",
    prominence: "20,194ft (6,155 m)",
    rank: 1,
    location: "Denali National Park and Preserve",
  },
  AZ: {
    state: "Arizona",
    highest_natural_point: "Humphreys Peak",
    elevation: " 12,636 ft (3,852 m)",
    prominence: "6,039 ft (1,841 m)",
    rank: 12,
    location: "the Kachina Peaks Wilderness in the Coconino National Forest",
  },
  AR: {
    state: "Arkansas",
    highest_natural_point: "Mount Magazine",
    elevation: ": 2,753 ft (839 m)",
    prominence: "2,143 ft (653 m)",
    rank: 37,
    location: "Mount Magazine State Park",
  },
  CA: {
    state: "California",
    highest_natural_point: "Mount Whitney (otherwise known as Tumanguya)",
    elevation: " 14,505ft (4,421 m)",
    prominence: "10,075 ft (3,071 m)",
    rank: 2,
    location: "Inya and Tulaire counties including Sequoia National Park",
  },
  CO: {
    state: "Colorado",
    highest_natural_point: "Mount Elbert",
    elevation: ": 14,440 ft (4401.2 m)",
    prominence: "9093 ft (2772 m)",
    rank: 3,
    location: "Lake County and part of the Rocky Mountains",
  },
  CT: {
    state: "Connecticut",
    highest_natural_point: "Mount Frissel",
    elevation: ": 2,454 ft (748 m)",
    prominence: "781 ft (238 m)",
    rank: 36,
    location: "Salisbury at the state line",
    trail: "Mount Frissel Trail",
  },
  DE: {
    state: "Delaware",
    highest_natural_point: "Highest benchmark monument is Ebright Azimuth",
    elevation: " 448 ft (137 m)",
    prominence: "32ft (9.8m)",
    rank: 49,
    location: "New Castle County",
  },
  FL: {
    state: "Florida",
    highest_natural_point: "Britton Hill",
    elevation: ": 345 ft (105 m)",
    prominence: "65 ft (20 m)",
    rank: 50,
    location: "Walton County near Lakewood",
  },
  GA: {
    state: "Georgia",
    highest_natural_point:
      "Brasstown Bald (located in the Blue Ridge Mountains)",
    elevation: ": 4,784 ft (1,458 m)",
    prominence: "2,108 ft (643 m)",
    rank: 25,
    location: "between Towns and Union counties",
  },
  HI: {
    state: "Hawaii",
    highest_natural_point: "Mauna Kea",
    elevation: ": 4,207.3m (13,803 ft)",
    prominence: "4,207.3m (13, 803 ft)",
    rank: 6,
    location: "Hawai’i County",
  },
  ID: {
    state: "Idaho",
    highest_natural_point: "Borah Peak (also known as Mount Borah)",
    elevation: " 12,662 ft (2,859 m)",
    prominence: "5,982 ft (1,823 m)",
    rank: 11,
    location: "within the Challis National Forest in the Lost River Range",
  },
  IL: {
    state: "Illinois",
    highest_natural_point: "Charles Mound ( a high hill)",
    elevation: ": 1,235 ft (376 m)",
    prominence: " 95ft (29m)",
    rank: 45,
    location: "Scales Mound Township",
  },
  IN: {
    state: "Indiana",
    highest_natural_point: "Hoosier Hill",
    elevation: ": 1,257 ft (383 m)",
    prominence: "297ft (91m)",
    rank: 44,
    location: "Franklin Township",
  },
  IA: {
    state: "Iowa",
    highest_natural_point: "Hawkeye Point",
    elevation: ": 1,670 ft (510 m)",
    prominence: "40 ft (12 m)",
    rank: 42,
    location: "Osceola County",
  },
  KS: {
    state: "Kansas",
    highest_natural_point: "Mount Sunflower",
    elevation: ": 4,039 ft (1,231 m)",
    prominence: "19ft (5.8m)",
    rank: 28,
    location: "Wallace County",
  },
  KY: {
    state: "Kentucky",
    highest_natural_point: "Black Mountain",
    elevation: ": 4,145 ft (1,263 m)",
    prominence: "1,905 ft (581 m)",
    rank: 27,
    location: "Harlan County",
  },
  LA: {
    state: "Louisiana",
    highest_natural_point: "Driskill Mountain",
    elevation: ": 535 ft (163 m)",
    prominence: "225 ft (69 m)",
    rank: 48,
    location: "Bienville Parish",
  },
  ME: {
    state: "Maine",
    highest_natural_point: "Mount Katahdin",
    elevation: ": 5,269 ft (1,606 m)",
    prominence: "4,228 ft (1,307 m)",
    rank: 22,
    location: "Northeast Piscataquis in the Appalachian Mountains",
  },
  MD: {
    state: "Maryland",
    highest_natural_point: "Hoye-Crest (summit)",
    elevation: ": 3,360 ft (1,024 m)",
    prominence: "80 ft (24 m)",
    rank: 32,
    location: "Garrett County along Backbone Mountain",
  },
  MA: {
    state: "Massachusetts",
    highest_natural_point: "Mount Greylock",
    elevation: ": 3,489 ft (1,063 m)",
    prominence: "2,463 ft (1,063 m)",
    rank: 31,
    location: "Adams in the Taconic Mountains",
  },
  MI: {
    state: "Michigan",
    highest_natural_point: "Mount Arvon",
    elevation: ": 1,979 ft (603 m)",
    prominence: "948ft (289 m)",
    rank: 38,
    location: "Marquette County in the Huron Mountains",
  },
  MN: {
    state: "Minnesota",
    highest_natural_point: "Eagle Mountain ",
    elevation: ": 2,301 ft (701 m)",
    prominence: "1,321 ft (403 m)",
    rank: 37,
    location: "Cook Country in the Misquah Hills",
  },
  MS: {
    state: "Mississippi",
    highest_natural_point: "Woodall Mountain",
    elevation: ": 806 ft (246 m)",
    prominence: "296 ft (90 m)",
    rank: 47,
    location: "Tishomingo County in the Southwest Appalachian Mountains",
  },
  MO: {
    state: "Missouri",
    highest_natural_point: "Taum Sauk Mountain",
    elevation: ": 1,772 ft (540 m)",
    prominence: "512 ft (156 m)",
    rank: 41,
    location: "the Saint Francois Mountains",
  },
  MT: {
    state: "Montana",
    highest_natural_point: "Granite Peak",
    elevation: ": 12,807 ft (3,904 m)",
    prominence: "4,759 ft (1,451 m)",
    rank: 10,
    location: "the Absaroka-Beartooth Wilderness in the Beartooth Mountains",
  },
  NE: {
    state: "Nebraska",
    highest_natural_point: "Panorama Point",
    elevation: ": 5,429 ft (1,655 m)",
    prominence: "26 ft (7.9 m)",
    rank: 20,
    location: "Kimball County",
  },
  NV: {
    state: "Nevada",
    highest_natural_point: "Boundary Peak",
    elevation: ": 13,147 ft (4,007 m)",
    prominence: "253 ft (77 m)",
    rank: 9,
    location: "Boundary Peak Wilderness of the Inyo National Forest",
  },
  NH: {
    state: "New Hampshire",
    highest_natural_point: "Mount Washington",
    elevation: ": 6,288.3 ft (1,916.7 m)",
    prominence: "6,148 ft (1,874 m)",
    rank: 18,
    location: "Sargent’s Purchase in the Presidential Range",
  },
  NJ: {
    state: "New Jersey",
    highest_natural_point: "High Point",
    elevation: ": 1,804 ft (550 m)",
    prominence: "833 ft (269 m)",
    rank: 40,
    location: "Sussex County in the Kittatinny Mountains",
  },
  NM: {
    state: "New Mexico",
    highest_natural_point: "Wheeler Peak",
    elevation: ": 13,167 ft (4,013 m)",
    prominence: "3,409 ft (1,039 m)",
    rank: 8,
    location: "Taos County in the Taos Mountains",
  },
  NY: {
    state: "New York",
    highest_natural_point: "Mount Marcy",
    elevation: ": 5,343 ft (1,629 m)",
    prominence: "4,914 ft (1,498 m)",
    rank: 21,
    location: "Essex County in the Adirondack Mountains",
  },
  NC: {
    state: "North Carolina",
    highest_natural_point: "Mount Mitchell",
    elevation: ": 6,684 ft (2,037 m)",
    prominence: "6,089 ft (1,856 m)",
    rank: 16,
    location: "Yancey County in the Appalachian Mountains",
  },
  ND: {
    state: "North Dakota",
    highest_natural_point: "White Butte",
    elevation: ": 3,508 ft (1,069 m)",
    prominence: "546 ft (166 m)",
    rank: 30,
    location: "Little Missouri National Grassland",
  },
  OH: {
    state: "Ohio",
    highest_natural_point: "Campbell Hill",
    elevation: ": 1,549.09 ft (472.16 m)",
    prominence: "639 ft (195 m)",
    rank: 43,
    location: "Bellefontaine",
  },
  OK: {
    state: "Oklahoma",
    highest_natural_point: "Black Mesa",
    elevation: ": 4,973ft (1,516 m)",
    prominence: "Unknown",
    rank: 23,
    location: "Cimarron County",
  },
  OR: {
    state: "Oregon",
    highest_natural_point: "Mount Hood",
    elevation: ": 11,249 ft (3,429 m)",
    prominence: "7,706 ft (2,349 m)",
    rank: 13,
    location: "the Cascade Volcanic Arc in the Cascade Range",
  },
  PA: {
    state: "Pennsylvania",
    highest_natural_point: "Mount Davis",
    elevation: ": 3,213 ft (979 m)",
    prominence: "653 ft (199 m)",
    rank: 33,
    location: "Forbes State Forest and part of the Allegheny Mountains",
  },
  RI: {
    state: "Rhode Island",
    highest_natural_point: "Jerimoth Hill",
    elevation: ": 811 ft (247 m)",
    prominence: "192 ft (59 m)",
    rank: 46,
    location: "Foster",
  },
  SC: {
    state: "South Carolina",
    highest_natural_point: "Sassafras Mountain",
    elevation: ": 3,554 ft (1,083 m)",
    prominence: "Unknown prominence",
    rank: 29,
    location: "Picken County and part of the Blue Ridge Mountains",
  },
  SD: {
    state: "South Dakota",
    highest_natural_point: "Black Elk Peak",
    elevation: ": 7,244 ft (2,208 m)",
    prominence: "2,922 ft (891 m)",
    rank: 15,
    location: "the Black Elk Wilderness in the Black Hills National Forest",
  },
  TN: {
    state: "Tennessee",
    highest_natural_point: "Clingmans Dome (Kuwahi in Cherokee)",
    elevation: ": 6,643 ft (2,025 m)",
    prominence: "4,503 ft (1,373 m)",
    rank: 17,
    location: "the Great Smoky Mountains National Park",
  },
  TX: {
    state: "Texas",
    highest_natural_point: "Guadalupe Peak",
    elevation: ": 8,751 ft (2,667 m)",
    prominence: "3,029  ft (923 m)",
    rank: 14,
    location: "Culberson County in the Guadalupe Mountains",
  },
  UT: {
    state: "Utah",
    highest_natural_point: "Kings Peak",
    elevation: ": 13,528 ft (4,123 m)",
    prominence: "6,348  ft (1,935 m)",
    rank: 7,
    location: "Duchesne County in the Uinta Mountains",
  },
  VT: {
    state: "Vermont",
    highest_natural_point: "Mount Mansfield",
    elevation: ": 4,395 ft (1,340 m)",
    prominence: "3,633  ft (1,107 m)",
    rank: 26,
    location: "Underhill and part of the Green Mountains",
  },
  VA: {
    state: "Virginia",
    highest_natural_point: "Mount Rogers",
    elevation: ": 5,730 ft (1,750 m)",
    prominence: "2,449 ft (746 m)",
    rank: 19,
    location:
      "on the border of Grayson and Smyth Counties and part of the Blue Ridge Mountains",
  },
  WA: {
    state: "Washington",
    highest_natural_point: "Mount Rainier (Tahoma)",
    elevation: ": 14,417 ft (4,394 m)",
    prominence: "13,246 ft (4,037 m)",
    rank: 4,
    location: "Mount Rainier National Park and part of the Cascade Range",
  },
  WV: {
    state: "West Virginia",
    highest_natural_point: "Spruce Mountain",
    elevation: ": 4,863 ft (1,482 m)",
    prominence: " 4,863 ft (1,482 m)",
    rank: 24,
    location: "Pendleton County and part of the Allegheny Mountains",
  },
  WI: {
    state: "Wisconsin",
    highest_natural_point: "Timms Hill",
    elevation: ": 1,951.5 ft (594.8 m)",
    prominence: " 425 ft (130 m)",
    rank: 39,
    location: "Price County in Timma Hill County Park",
  },
  WY: {
    state: "Wyoming",
    highest_natural_point: "Gannett Peak",
    elevation: ": 13,810 ft (4,210 m)",
    prominence: "7,076 ft (2,157 m)",
    rank: 5,
    location: "the Bridger Wilderness and part of the Wind River Range",
  },
};
